/** Domain enums shared between engine, admin and player clients. */

export enum UserRole {
  PLAYER = "PLAYER",
  SUPPORT = "SUPPORT",
  KYC_OFFICER = "KYC_OFFICER",
  PAYMENTS = "PAYMENTS",
  RISK = "RISK",
  AFFILIATE_MANAGER = "AFFILIATE_MANAGER",
  MARKETING = "MARKETING",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export const ADMIN_ROLES: UserRole[] = [
  UserRole.SUPPORT,
  UserRole.KYC_OFFICER,
  UserRole.PAYMENTS,
  UserRole.RISK,
  UserRole.AFFILIATE_MANAGER,
  UserRole.MARKETING,
  UserRole.ADMIN,
  UserRole.SUPER_ADMIN,
];

export enum UserStatus {
  ACTIVE = "ACTIVE",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
  SUSPENDED = "SUSPENDED",
  SELF_EXCLUDED = "SELF_EXCLUDED",
  BANNED = "BANNED",
}

export enum KycStatus {
  NOT_STARTED = "NOT_STARTED",
  PENDING = "PENDING",
  IN_REVIEW = "IN_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}

export enum WalletType {
  REAL = "REAL",
  BONUS = "BONUS",
  DEMO = "DEMO",
}

/** Double-entry ledger account classification. */
export enum LedgerAccountType {
  PLAYER_REAL = "PLAYER_REAL",
  PLAYER_BONUS = "PLAYER_BONUS",
  PLAYER_DEMO = "PLAYER_DEMO",
  HOUSE = "HOUSE",
  PSP_CLEARING = "PSP_CLEARING",
  BONUS_POOL = "BONUS_POOL",
  JACKPOT_POOL = "JACKPOT_POOL",
  AFFILIATE_POOL = "AFFILIATE_POOL",
  TAX_PAYABLE = "TAX_PAYABLE",
}

export enum LedgerDirection {
  DEBIT = "DEBIT",
  CREDIT = "CREDIT",
}

export enum TxType {
  DEPOSIT = "DEPOSIT",
  WITHDRAWAL = "WITHDRAWAL",
  BET = "BET",
  WIN = "WIN",
  REFUND = "REFUND",
  BONUS_CREDIT = "BONUS_CREDIT",
  BONUS_WAGER = "BONUS_WAGER",
  BONUS_FORFEIT = "BONUS_FORFEIT",
  ADJUSTMENT = "ADJUSTMENT",
  AFFILIATE_COMMISSION = "AFFILIATE_COMMISSION",
  CASHBACK = "CASHBACK",
  RAKEBACK = "RAKEBACK",
  JACKPOT = "JACKPOT",
  FEE = "FEE",
  CHARGEBACK = "CHARGEBACK",
  TIP = "TIP",
  TOURNAMENT_PRIZE = "TOURNAMENT_PRIZE",
}

export enum TxStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  REVERSED = "REVERSED",
  ON_HOLD = "ON_HOLD",
}

export enum PaymentMethod {
  CARD = "CARD",
  BANK_TRANSFER = "BANK_TRANSFER",
  E_WALLET = "E_WALLET",
  CRYPTO = "CRYPTO",
  PAPARA = "PAPARA",
  PAYFIX = "PAYFIX",
  MANUAL = "MANUAL",
}

export enum GameCategory {
  SLOTS = "SLOTS",
  LIVE_CASINO = "LIVE_CASINO",
  TABLE = "TABLE",
  CRASH = "CRASH",
  INSTANT = "INSTANT",
  JACKPOT = "JACKPOT",
  VIRTUAL = "VIRTUAL",
  SPORTS = "SPORTS",
  FISHING = "FISHING",
  LOTTERY = "LOTTERY",
}

export enum GameProvider {
  INTERNAL = "INTERNAL",
  AGGREGATOR = "AGGREGATOR",
}

export enum RoundStatus {
  OPEN = "OPEN",
  ACTIVE = "ACTIVE",
  SETTLED = "SETTLED",
  CANCELLED = "CANCELLED",
}

export enum BetStatus {
  PLACED = "PLACED",
  ACTIVE = "ACTIVE",
  WON = "WON",
  LOST = "LOST",
  CASHED_OUT = "CASHED_OUT",
  VOID = "VOID",
}

export enum BonusType {
  WELCOME = "WELCOME",
  DEPOSIT_MATCH = "DEPOSIT_MATCH",
  FREE_SPINS = "FREE_SPINS",
  RELOAD = "RELOAD",
  CASHBACK = "CASHBACK",
  LOYALTY = "LOYALTY",
  TOURNAMENT = "TOURNAMENT",
  DROPS_WINS = "DROPS_WINS",
  REFERRAL = "REFERRAL",
}

export enum BonusStatus {
  AVAILABLE = "AVAILABLE",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
  FORFEITED = "FORFEITED",
}

export enum VipTier {
  BRONZE = "BRONZE",
  SILVER = "SILVER",
  GOLD = "GOLD",
  PLATINUM = "PLATINUM",
  DIAMOND = "DIAMOND",
  VIP_BLACK = "VIP_BLACK",
}

export enum NotificationChannel {
  EMAIL = "EMAIL",
  SMS = "SMS",
  PUSH = "PUSH",
  IN_APP = "IN_APP",
}

export enum AuditAction {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  LOGIN_FAILED = "LOGIN_FAILED",
  REGISTER = "REGISTER",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  PASSWORD_RESET = "PASSWORD_RESET",
  TWO_FA_ENABLED = "TWO_FA_ENABLED",
  TWO_FA_DISABLED = "TWO_FA_DISABLED",
  BALANCE_ADJUSTMENT = "BALANCE_ADJUSTMENT",
  USER_UPDATED = "USER_UPDATED",
  USER_SUSPENDED = "USER_SUSPENDED",
  KYC_UPDATED = "KYC_UPDATED",
  DEPOSIT_APPROVED = "DEPOSIT_APPROVED",
  WITHDRAWAL_APPROVED = "WITHDRAWAL_APPROVED",
  WITHDRAWAL_REJECTED = "WITHDRAWAL_REJECTED",
  BONUS_CREATED = "BONUS_CREATED",
  BONUS_UPDATED = "BONUS_UPDATED",
  SETTINGS_UPDATED = "SETTINGS_UPDATED",
  CMS_EDIT = "CMS_EDIT",
  CMS_PUBLISH = "CMS_PUBLISH",
  GAME_UPDATED = "GAME_UPDATED",
  ROLE_CHANGED = "ROLE_CHANGED",
  IMPERSONATION = "IMPERSONATION",
  LIMIT_SET = "LIMIT_SET",
  API_KEY_ROTATED = "API_KEY_ROTATED",
}

export enum LimitType {
  DEPOSIT = "DEPOSIT",
  LOSS = "LOSS",
  SESSION = "SESSION",
  WAGER = "WAGER",
}
